spring.application.name=inteligencia-service

spring.threads.virtual.enabled=true

server.port=8084

eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
eureka.instance.hostname=inteligencia-service