spring.application.name=inteligencia-service

spring.threads.virtual.enabled=true

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

#spring.cloud.openfeign.eager-load.enabled=true
#spring.cloud.openfeign.eager-load.clients=estabelecimento-saude,estoque-service,insumos,movimentacao-service

services.estoque=http://localhost:8085
services.movimentacao=http://localhost:8082
services.insumos=http://localhost:8088
services.estabelecimento-saude=http://localhost:8081
